routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//RUTAS DEL FRONT

Route::get('/', ['as' => 'front.index',
 'uses' => 'FrontController@index'
]);

Route::get('categories/{name}', [
  'uses' => 'FrontController@searchCategory',
  'as' => 'front.search.category'
]);
Route::get('tags/{name}', [
  'uses' => 'FrontController@searchTag',
  'as' => 'front.search.tag'
]);

Route::get('articles/{slug}', [
		'uses'	=> 'FrontController@viewArticle',
		'as'	=>	'front.view.article'
	]);


//RUTAS DEL ADMIN
Route::group(['prefix' => 'admin', 'middleware' => ['auth','admin']], function(){

        Route::get('/', ['as' => 'admin.index', function() {
           return view('admin.index');
        }]);
        Route::group(['middleware' => 'admin'], function(){
              Route::resource('users','UsersController');
              Route::get('users/{id}/destroy',[
                'uses' => 'UsersController@destroy',
                'as' => 'users.destroy'
              ]);
        });
        Route::resource('categories', 'CategoriesController');
        Route::get('categories/{id}/destroy',[
          'uses' => 'CategoriesController@destroy',
          'as' => 'categories.destroy'
        ]);
        Route::resource('tags', 'TagsController');
        Route::get('tags/{id}/destroy',[
          'uses' => 'TagsController@destroy',
          'as' => 'tags.destroy'
        ]);
        Route::resource('articles', 'ArticlesController');
        Route::get('articles/{id}/destroy',[
          'uses' => 'ArticlesController@destroy',
          'as' => 'articles.destroy'
        ]);
        Route::get('images', [
          'uses' => 'ImagesController@index',
          'as' => 'images.index']);

  });
  Auth::routes(); //---- NECESARIO PARA EL METODO AUTH

resources/views/admin/template/partials/errors.blade.php
@if(count($errors) > 0)
  <div class="alert alert-danger" role="alert">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
   </ul>
</div>
@endif

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {{-- <img alt="Ing. Torres" class="admin-logo-nav" src="{{ asset('images/logo.png') }}"> --}}
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        @if(Auth::user())
          <li><a href="{{ route('admin.index')}}">Inicio</a></li>
        @if(Auth::user()->TypeAdmin())
          <li><a href="{{ route('users.index') }}">Usuarios</a></li>
        @endif
          <li><a href="{{ route('categories.index')}}">Categorias</a></li>
          <li><a href="{{ route('articles.index') }}">Articulos</a></li>
          <li><a href="{{ route('images.index') }}">Imagenes</a></li>
          <li><a href="{{ route('tags.index')}}">Tags</a></li>
        @endif

      </ul>

      {{-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> --}}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ route('front.index') }}" target="">Pagina Principal</a></li>
        @if (Auth::guest())
            <li><a href="{{ route('login') }}">Login</a></li>


        @else
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
                            Logout
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>
            </li>
        @endif
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>